### ISSUE TITLE
Change /api/update Failure response

### ISSUE THREAD

**Issue by PotentialStyx** [pieromqwerty/ReplNet#3]
The failure response on /api/update is currently:
> IDK how, but I somehow failed

This is inconsistent with the failure response of every other endpoint (`{'status': 'Failure', 'additional_info': '<info>'}`). Also there are many ways this operation could fail and the server should be able to return that info to the client.

# ⚠️ This would require a new major release as this is a breaking change. ⚠️

**Comment by piemadd** [comment]
Poop
